# Generated by Django 3.1.7 on 2021-02-27 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentInformation',
            fields=[
                ('depart_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'dp_inf',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.useraccount')),
                ('result', models.IntegerField()),
            ],
            options={
                'db_table': 'test_results',
            },
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.useraccount')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=30)),
                ('position', models.CharField(default='Сотрудник', max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('office', models.CharField(max_length=15)),
                ('is_head', models.BooleanField()),
                ('department_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.departmentinformation')),
            ],
            options={
                'db_table': 'user_inf',
            },
        ),
    ]
