# Generated by Django 3.1.7 on 2021-02-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_departmentinformation_testresult_userinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='second_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='user_id',
            new_name='user',
        ),
    ]
