# Generated by Django 3.1.7 on 2021-02-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210227_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.departmentinformation'),
        ),
    ]
