# Generated by Django 3.1.7 on 2021-02-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210228_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='department',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_head',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='office',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='position',
        ),
    ]
