# Generated by Django 3.1.7 on 2021-02-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210228_1457'),
        ('home', '0004_auto_20210227_2015'),
    ]

    operations = [
    ]
